version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gym_network

  redis:
    image: redis:7-alpine
    container_name: gym_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gym_network

volumes:
  postgres_data:
  redis_data:

networks:
  gym_network:
    driver: bridge
