export enum UserRole {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum MembershipStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CheckInStatus {
  ALLOWED = 'ALLOWED',
  DENIED = 'DENIED',
}

export enum NotificationType {
  REGISTRATION_APPROVED = 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
  MEMBERSHIP_EXPIRING = 'MEMBERSHIP_EXPIRING',
  MEMBERSHIP_EXPIRED = 'MEMBERSHIP_EXPIRED',
  NEW_REGISTRATION = 'NEW_REGISTRATION',
  CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS',
  CHECK_IN_DENIED = 'CHECK_IN_DENIED',
}
